version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_AMQP_PORT: ${RABBITMQ_AMQP_PORT}
      RABBITMQ_AMQP_HOST: ${RABBITMQ_AMQP_HOST}
      COMMANDS_PATH: ${COMMANDS_PATH}
    network_mode: host
    volumes:
      - ./resources:/resources
